### ISSUE TITLE
GAX - GNTM Aktien Index

### ISSUE THREAD

**Issue by BikoKiessling** [wolkoman/gntmhub#3]
Currently, there is no way to directly get insight into which models are the top selling bitches on the market. As we're talking about human trade here and as our dearest of friends Sir Darwin said "only the fittest models of germany will surive." So, in order to make this process as seamless as possible, we need an index to keep track of the high sellers. I propose the name of Gax to really hold it kurz and knackig. THanks

**Comment by wolkoman** [comment]
Clarification needed. At the moment the current stock price already tells the user which models are high in demand and which are not. This is shown in the application by the number in the bottom left corner of each candidate. Which further feature would you suggest?
![image](https://user-images.githubusercontent.com/8089982/107886194-9c6bef80-6efe-11eb-9a48-7b6fd1b0ef88.png)

PS.: The name GAX will be suiting in all cases I am sure 😄

**Comment by BikoKiessling** [comment]
Hmm, very true. Maybe a timely graph of the stocks of the most used models. But I think this is going overboard. Just needed some attention because I was feeling lonely. Thanks for listening to me. Feel more complete now. Programmers do have a heart after all!

**Comment by BikoKiessling** [comment]
Happy Valentine's!

**Comment by wolkoman** [comment]
Happy Valentine's ♥ :)
