### ISSUE TITLE
Scrollbar missing & not being able to scroll in Firefox

### ISSUE THREAD

**Issue by rieschla** [wolkoman/gntmhub#7]
![grafik](https://user-images.githubusercontent.com/10473431/152632807-659386cb-2bce-4548-b3d4-0c2c91475e48.png)

**Comment by rieschla** [comment]
Schaut so aus, als wär "overflow-y: overlay" depracated und nicht kompatibel mit Firefox :(

https://caniuse.com/css-overflow-overlay
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#values

**Comment by wolkoman** [comment]
Thanks for the issue!

**Comment by rieschla** [comment]
No problem bro :)
